### ISSUE TITLE
import shapely.geometry

### ISSUE THREAD

**Issue by ncp1113** [lexelby/inkstitch#50] opened 2018-02-01 16:05 UTC
I am getting the following error using a MacBook Pro with High Sierra 10.13.2 Python 2.7.14 :: Anaconda custom (64-bit)

Traceback (most recent call last):
 File "embroider.py", line 31 in <module>
  import shapely.geometry as shgeo
Import Error: No module named shapely.geometry

This is wierd because I tried importing shapely.geometry in a python console and I had no problem importing it.  I tried doing the same from the directory that Inkscape is launched from Applications/Inkscape.app/Contents/Resources/bin/ with no problem

Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely.geometry as shgeo

gave no errors.

**Comment by AkiraNorthstar** [comment] 2018-02-01 19:49
Do you test with: import shapely.geometry as or without as?
Sometimes import as is a bit tricky: https://www.python.org/dev/peps/pep-0221/
Shapely was updated the last eight days on conda-forge, so if not already made, update to the latest and test again.
That it works from the bin directory is, that all dependencies are met (comiled in).
I hope that helps.

**Comment by ncp1113** [comment] 2018-02-01 20:19
Thanks for your response. I am not sure what you mean by "import shapely.geometry as or without as”.  I have successfully imported it in a shell from the inkscape/bin directory and from  my home directory. 

I installed shapely from condo-forge. Here is the output:

Downloading and Extracting Packages
shapely 1.6.4: ######################################################### | 100% 
certifi 2017.11.5: ##################################################### | 100% 
openssl 1.0.2n: ######################################################## | 100% 
ca-certificates 2017.11.5: ############################################# | 100% 
geos 3.6.2: ############################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Nancys-MacBook-Pro:QuiltRoulette nancy$ conda search shapely --channel conda-forge
Loading channels: done
Name                       Version                   Build  Channel        
shapely                    1.3.1                    py26_0  defaults       
shapely                    1.3.1                    py27_0  defaults       
shapely                    1.3.1                    py33_0  defaults       
shapely                    1.3.2                    py26_0  defaults       
shapely                    1.3.2                    py27_0  defaults       
shapely                    1.3.2                    py33_0  defaults       
shapely                    1.3.2                    py34_0  defaults       
shapely                    1.4.0                    py26_0  defaults       
shapely                    1.4.0                    py27_0  defaults       
shapely                    1.4.0                    py33_0  defaults       
shapely                    1.4.0                    py34_0  defaults       
shapely                    1.4.1                    py26_0  defaults       
shapely                    1.4.1                    py27_0  defaults       
shapely                    1.4.1                    py33_0  defaults       
shapely                    1.4.1                    py34_0  defaults       
shapely                    1.4.4                    py26_0  defaults       
shapely                    1.4.4                    py27_0  defaults       
shapely                    1.4.4                    py33_0  defaults       
shapely                    1.4.4                    py34_0  defaults       
shapely                    1.5.0                    py26_0  defaults       
shapely                    1.5.0                    py27_0  defaults       
shapely                    1.5.0                    py33_0  defaults       
shapely                    1.5.0                    py34_0  defaults       
shapely                    1.5.1                    py26_0  defaults       
shapely                    1.5.1                    py27_0  defaults       
shapely                    1.5.1                    py33_0  defaults       
shapely                    1.5.1                    py34_0  defaults       
shapely                    1.5.2                    py26_0  defaults       
shapely                    1.5.2                    py27_0  defaults       
shapely                    1.5.2                    py33_0  defaults       
shapely                    1.5.2                    py34_0  defaults       
shapely                    1.5.5                    py26_0  defaults       
shapely                    1.5.5                    py27_0  defaults       
shapely                    1.5.5                    py33_0  defaults       
shapely                    1.5.5                    py34_0  defaults       
shapely                    1.5.6                    py26_0  defaults       
shapely                    1.5.6                    py27_0  defaults       
shapely                    1.5.6                    py33_0  defaults       
shapely                    1.5.6                    py34_0  defaults       
shapely                    1.5.7                    py26_0  defaults       
shapely                    1.5.7                    py27_0  defaults       
shapely                    1.5.7                    py33_0  defaults       
shapely                    1.5.7                    py34_0  defaults       
shapely                    1.5.8                    py26_0  defaults       
shapely                    1.5.8                    py27_0  defaults       
shapely                    1.5.8                    py33_0  defaults       
shapely                    1.5.8                    py34_0  defaults       
shapely                    1.5.9                    py26_0  defaults       
shapely                    1.5.9                    py27_0  defaults       
shapely                    1.5.9                    py33_0  defaults       
shapely                    1.5.9                    py34_0  defaults       
shapely                    1.5.11                   py27_0  defaults       
shapely                    1.5.11                   py34_0  defaults       
shapely                    1.5.11                   py35_0  defaults       
shapely                    1.5.13              np110py27_1  conda-forge    
shapely                    1.5.13              np110py34_1  conda-forge    
shapely                    1.5.13              np110py35_1  conda-forge    
shapely                    1.5.13               np18py27_1  conda-forge    
shapely                    1.5.13               np18py34_1  conda-forge    
shapely                    1.5.13               np19py27_1  conda-forge    
shapely                    1.5.13               np19py34_1  conda-forge    
shapely                    1.5.13               np19py35_1  conda-forge    
shapely                    1.5.13                   py27_0  conda-forge    
shapely                    1.5.13                   py27_0  defaults       
shapely                    1.5.13                   py34_0  conda-forge    
shapely                    1.5.13                   py34_0  defaults       
shapely                    1.5.13                   py35_0  defaults       
shapely                    1.5.15              np110py27_0  conda-forge    
shapely                    1.5.15              np110py34_0  conda-forge    
shapely                    1.5.15              np110py35_0  conda-forge    
shapely                    1.5.15              np111py27_0  conda-forge    
shapely                    1.5.15              np111py34_0  conda-forge    
shapely                    1.5.15              np111py35_0  conda-forge    
shapely                    1.5.15               np19py27_0  conda-forge    
shapely                    1.5.15               np19py34_0  conda-forge    
shapely                    1.5.15               np19py35_0  conda-forge    
shapely                    1.5.16              np110py27_0  conda-forge    
shapely                    1.5.16              np110py27_1  conda-forge    
shapely                    1.5.16              np110py34_0  conda-forge    
shapely                    1.5.16              np110py34_1  conda-forge    
shapely                    1.5.16              np110py35_0  conda-forge    
shapely                    1.5.16              np110py35_1  conda-forge    
shapely                    1.5.16              np111py27_0  conda-forge    
shapely                    1.5.16              np111py27_1  conda-forge    
shapely                    1.5.16              np111py34_0  conda-forge    
shapely                    1.5.16              np111py34_1  conda-forge    
shapely                    1.5.16              np111py35_0  conda-forge    
shapely                    1.5.16              np111py35_1  conda-forge    
shapely                    1.5.16                   py27_0  defaults       
shapely                    1.5.16                   py34_0  defaults       
shapely                    1.5.16                   py35_0  defaults       
shapely                    1.5.17              np110py27_0  conda-forge    
shapely                    1.5.17              np110py27_1  conda-forge    
shapely                    1.5.17              np110py27_2  conda-forge    
shapely                    1.5.17              np110py34_0  conda-forge    
shapely                    1.5.17              np110py34_1  conda-forge    
shapely                    1.5.17              np110py34_2  conda-forge    
shapely                    1.5.17              np110py35_0  conda-forge    
shapely                    1.5.17              np110py35_1  conda-forge    
shapely                    1.5.17              np110py35_2  conda-forge    
shapely                    1.5.17              np110py36_2  conda-forge    
shapely                    1.5.17              np111py27_0  conda-forge    
shapely                    1.5.17              np111py27_1  conda-forge    
shapely                    1.5.17              np111py27_2  conda-forge    
shapely                    1.5.17              np111py27_3  conda-forge    
shapely                    1.5.17              np111py34_0  conda-forge    
shapely                    1.5.17              np111py34_1  conda-forge    
shapely                    1.5.17              np111py34_2  conda-forge    
shapely                    1.5.17              np111py35_0  conda-forge    
shapely                    1.5.17              np111py35_1  conda-forge    
shapely                    1.5.17              np111py35_2  conda-forge    
shapely                    1.5.17              np111py35_3  conda-forge    
shapely                    1.5.17              np111py36_2  conda-forge    
shapely                    1.5.17              np111py36_3  conda-forge    
shapely                    1.5.17              np112py27_2  conda-forge    
shapely                    1.5.17              np112py27_3  conda-forge    
shapely                    1.5.17              np112py35_2  conda-forge    
shapely                    1.5.17              np112py35_3  conda-forge    
shapely                    1.5.17              np112py36_2  conda-forge    
shapely                    1.5.17              np112py36_3  conda-forge    
shapely                    1.5.17              np113py27_3  conda-forge    
shapely                    1.5.17              np113py35_3  conda-forge    
shapely                    1.5.17              np113py36_3  conda-forge    
shapely                    1.5.17                   py27_4  conda-forge    
shapely                    1.5.17                   py35_4  conda-forge    
shapely                    1.5.17                   py36_4  conda-forge    
shapely                    1.6.0                    py27_0  conda-forge    
shapely                    1.6.0                    py35_0  conda-forge    
shapely                    1.6.0                    py36_0  conda-forge    
shapely                    1.6.1                    py27_0  conda-forge    
shapely                    1.6.1                    py27_1  conda-forge    
shapely                    1.6.1            py27h13f9126_2  defaults       
shapely                    1.6.1                    py35_0  conda-forge    
shapely                    1.6.1                    py35_1  conda-forge    
shapely                    1.6.1            py35hc800253_2  defaults       
shapely                    1.6.1                    py36_0  conda-forge    
shapely                    1.6.1                    py36_1  conda-forge    
shapely                    1.6.1            py36h2d2fe67_2  defaults       
shapely                    1.6.2                    py27_0  conda-forge    
shapely                    1.6.2                    py27_1  conda-forge    
shapely                    1.6.2            py27h7c2deba_0  defaults       
shapely                    1.6.2                    py35_0  conda-forge    
shapely                    1.6.2                    py35_1  conda-forge    
shapely                    1.6.2            py35h5da8405_0  defaults       
shapely                    1.6.2                    py36_0  conda-forge    
shapely                    1.6.2                    py36_1  conda-forge    
shapely                    1.6.2            py36hed20685_0  defaults       
shapely                    1.6.3                    py27_0  conda-forge    
shapely                    1.6.3                    py35_0  conda-forge    
shapely                    1.6.3                    py36_0  conda-forge    
shapely                    1.6.4                    py27_0  conda-forge    
shapely                    1.6.4                    py35_0  conda-forge    
shapely                    1.6.4                    py36_0  conda-forge 

I then ran Inkscape from the /Applications/Inkscape.app/Contents/Resources/bin
directory and got the same error. I ran it normally and also got the same error. 

I could not find an option for verbose output in Inkscape.

Nancy

**Comment by AkiraNorthstar** [comment] 2018-02-01 20:46
Sorry. When you test (manualy in the console) the import of shapley.geometry, do you write 
`import shapely.geometry as shgeo` , or only `import shapley.geometry` ?
It seems you are up to date with the versions. Which python version(s) do you have installed?
Depend of your python version you have to install the shapley package.
For python27: shapely 1.6.4 py27_0 conda-forge

**Comment by ncp1113** [comment] 2018-02-02 18:07
I use python 2.7, which is what conda is using. I have tried both ways to import shapely.geometry. As you can see, they both import without errors.
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely.geometry as shgeo
>>> import shapely.geometry
>>> 

I tried the same thing from the dir that Inkscape executes from

Nancys-MacBook-Pro:Financial nancy$ cd /Applications/Inkscape.app/Contents/Resources/bin/
Nancys-MacBook-Pro:bin nancy$ ls
gimp		inkscape	inkscape-bin
Nancys-MacBook-Pro:bin nancy$ python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapley.geometry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named shapley.geometry
>>> import shapely.geometry
>>> import shapely.geometry as shgeo
>>> 

I installed version 1.6.4 of shapely and it still imports fine

Nancys-MacBook-Pro:bin nancy$ pip install shapely==1.6.4
Collecting shapely==1.6.4
  Downloading Shapely-1.6.4-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 718kB/s 
Installing collected packages: shapely
  Found existing installation: Shapely 1.6.4.post1
    Uninstalling Shapely-1.6.4.post1:
      Successfully uninstalled Shapely-1.6.4.post1
Successfully installed shapely-1.6.4.post1
Nancys-MacBook-Pro:bin nancy$ python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct  5 2017, 02:28:52) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shapely.geometry
>>> import shapely.geometry as shgeo
>>> 


I think this is super weird. Why would it import okay everywhere but inside Inkscape? It makes no sense to me.

**Comment by AkiraNorthstar** [comment] 2018-02-02 19:08
Do you have /path/to/python/site-packages/shapely/geometry directory?
In fedora27 it is /usr/lib64/python2.7/site-packages/shapely/geometry.
Puhh, really strange! Any forgotten dependencies? numpy for example.

**Comment by ncp1113** [comment] 2018-02-02 21:12
Here is my pip list. 
nancy$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
anaconda-client (1.6.5)
anaconda-navigator (1.6.12)
anaconda-project (0.8.2)
anyjson (0.3.3)
appdirs (1.4.3)
appnope (0.1.0)
appscript (1.0.1)
argh (0.26.2)
asn1crypto (0.24.0)
astroid (1.6.0)
astropy (2.0.3)
attrs (17.3.0)
Automat (0.6.0)
awscli (1.14.12)
Babel (2.5.1)
backports-abc (0.5)
backports.functools-lru-cache (1.4)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)
bcrypt (3.1.4)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
bkcharts (0.2)
blaze (0.11.3)
bleach (2.1.2)
bokeh (0.12.13)
boto (2.48.0)
boto3 (1.5.2)
botocore (1.8.16)
Bottleneck (1.2.1)
cdecimal (2.3)
certifi (2018.1.18)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
cloudpickle (0.5.2)
clyent (1.2.2)
colorama (0.3.9)
colormath (3.0.0)
conda (4.4.2)
conda-build (3.0.27)
conda-verify (2.0.0)
configparser (3.5.0)
constantly (15.1.0)
contextlib2 (0.5.5)
coverage (4.4.2)
cryptography (2.1.4)
cycler (0.10.0)
cytoolz (0.9.0)
daemons (1.3.0)
dask (0.16.0)
datashape (0.5.4)
decorator (4.2.1)
distribute (0.7.3)
distributed (1.20.2)
Django (1.11.3)
django-admin-sortable (2.1)
django-allauth (0.25.2)
django-annoying (0.10.3)
django-bower (5.2.0)
django-braces (1.12.0)
django-contact-form (1.4.2)
django-cors-headers (2.1.0)
django-dbbackup (2.0.4)
django-extensions (1.9.8)
django-fixture-magic (0.1.3)
django-hreflang (1.7)
django-invitations (1.9.1)
django-ipware (1.1.6)
django-orm-magic (0.4)
django-selenium (0.9.8)
django-ses (0.8.4)
django-sslserver (0.19)
django-storages (1.6.5)
django-supervisor (0.4.0)
django-test-utils (0.3)
django-utils (0.0.2)
django-utils2 (2.4.0)
djorm-pgarray (1.2)
djutils (0.3.2)
docutils (0.14)
EasyProcess (0.2.3)
entrypoints (0.2.3)
enum-compat (0.0.2)
enum34 (1.1.6)
et-xmlfile (1.0.1)
eventlet (0.21.0)
fastcache (1.0.2)
filelock (2.0.13)
Flask (0.12.2)
Flask-Cors (3.0.3)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.2.0)
GDAL (2.2.0)
gevent (1.2.2)
glob2 (0.6)
gmpy2 (2.0.8)
greenlet (0.4.12)
grin (1.2.1)
h5py (2.7.1)
heapdict (1.0.0)
html5lib (1.0.1)
idna (2.6)
imageio (2.2.0)
imagesize (0.7.1)
incremental (17.5.0)
ipaddress (1.0.19)
ipykernel (4.7.0)
ipython (5.5.0)
ipython-genutils (0.2.0)
ipywidgets (7.0.5)
isort (4.2.15)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.11.1)
Jinja2 (2.10)
jmespath (0.9.3)
jsonfield (2.0.1)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.2.0)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
jupyterlab (0.30.6)
jupyterlab-launcher (0.7.0)
keyring (10.5.0)
lazy-object-proxy (1.3.1)
llvmlite (0.21.0)
locket (0.2.0)
lockfile (0.12.2)
lxml (4.1.1)
MarkupSafe (1.0)
matplotlib (2.1.1)
mccabe (0.6.1)
meld3 (1.0.2)
mistune (0.8.3)
mpmath (1.0.0)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
navigator-updater (0.1.0)
nbconvert (5.3.1)
nbformat (4.4.0)
networkx (2.0)
nltk (3.2.5)
nose (1.3.7)
notebook (5.2.2)
numba (0.36.1)
numexpr (2.6.4)
numpy (1.14.0)
numpydoc (0.7.0)
oauthlib (2.0.6)
odo (0.5.1)
olefile (0.44)
openpyxl (2.4.9)
packaging (16.8)
pandas (0.21.1)
pandocfilters (1.4.2)
paramiko (2.4.0)
parso (0.1.1)
partd (0.3.8)
path.py (10.5)
pathlib2 (2.3.0)
pathtools (0.1.2)
patsy (0.4.1)
pdfkit (0.6.1)
pep8 (1.7.1)
pexpect (4.3.1)
pickleshare (0.7.4)
Pillow (4.3.0)
pip (9.0.1)
pkginfo (1.4.1)
pluggy (0.6.0)
ply (3.10)
prompt-toolkit (1.0.15)
psutil (5.4.2)
psycopg2 (2.7.3.2)
ptyprocess (0.5.2)
py (1.5.2)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
PyAudio (0.2.7)
pycairo (1.15.4)
pycodestyle (2.3.1)
pycosat (0.6.3)
pycparser (2.18)
pycrypto (2.6.1)
pycurl (7.43.0.1)
pyflakes (1.6.0)
Pygments (2.2.0)
pygobject (3.22.0)
Pykka (1.2.1)
pylint (1.8.1)
PyNaCl (1.2.1)
pyodbc (4.0.21)
pyOpenSSL (17.5.0)
pyparsing (2.2.0)
pysftp (0.2.9)
PySocks (1.6.7)
pytest (3.3.1)
pytest-base-url (1.3.0)
pytest-html (1.14.2)
pytest-metadata (1.3.0)
pytest-selenium (1.9.1)
pytest-variables (1.5.1)
python-daemon (2.1.2)
python-dateutil (2.6.1)
python-openid (2.2.5)
python-utils (2.2.0)
pytz (2017.3)
PyVirtualDisplay (0.2.1)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.3)
QtAwesome (0.4.4)
qtconsole (4.3.1)
QtPy (1.3.1)
requests (2.18.4)
requests-oauthlib (0.8.0)
requests-toolbelt (0.8.0)
rope (0.10.7)
rsa (3.4.2)
ruamel-yaml (0.11.14)
s3transfer (0.1.12)
scandir (1.6)
scikit-image (0.13.1)
scikit-learn (0.19.1)
scipy (1.0.0)
seaborn (0.8.1)
selenium (3.8.0)
service-identity (17.0.0)
setuptools (38.2.4)
Shapely (1.6.4.post1)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.9)
spark-parser (1.8.5)
Spawning (0.9.7)
Sphinx (1.6.5)
sphinxcontrib-websupport (1.0.1)
spyder (3.2.4)
SQLAlchemy (1.1.15)
statsmodels (0.8.0)
subprocess32 (3.2.7)
supervisor (3.3.3)
sympy (1.1.1)
tables (3.4.2)
tblib (1.3.2)
terminado (0.8.1)
testpath (0.3.1)
toolz (0.9.0)
tornado (4.5.2)
traitlets (4.3.2)
Twisted (17.1.0)
typing (3.6.2)
uncompyle2 (2.0.0)
uncompyle6 (2.14.1)
unicodecsv (0.14.1)
uritemplate (3.0.0)
uritemplate.py (3.0.2)
urllib3 (1.22)
uWSGI (2.0.15)
virtualenv (15.1.0)
watchdog (0.8.3)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.13)
wheel (0.29.0)
widgetsnbextension (3.0.8)
wrapt (1.10.11)
WSGIserver (1.3)
wxPython (4.0.0b2)
xdis (3.6.3)
xlrd (1.1.0)
XlsxWriter (1.0.2)
xlwings (0.11.4)
xlwt (1.3.0)
zict (0.1.3)
zope.component (4.2.2)
zope.event (4.2.0)
zope.interface (4.0.5)


I found the shapely package with find here:
/anaconda2//pkgs/shapely-1.6.4-py27_0/lib/python2.7/site-packages/shapely
/anaconda2//lib/python2.7/site-packages/shapely

**Comment by lexelby** [comment] 2018-02-02 21:41
The problem is that inkscape brings its own Python with it and uses that when running extensions.  That one doesn't have shapely and such.

Ultimately, we'll figure out a similar installation method to the one we have for Linux, where inkstitch brings its dependencies with it.  We haven't gotten the build process working for Mac yet though.

Until then, try setting your python interpreter for inkscape: http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters

**Comment by ncp1113** [comment] 2018-02-03 15:45
Well.. I wouldn’t have thought of that. Just so you know, I followed the instructions in you link for changing the python interpreter that Inkscape uses. You can edit the preferences.xml file but when you relaunch Inkscape the file reverts to what it was. When I went back to Vim it asked me if I wanted to load the changed file. I tried keeping the file and saving it again with Inkscape open on the unlikely chance that Inkscape would read that file. It didn’t.  

If I have time I will try loading Shapely as an extension.

Nancy

**Comment by lexelby** [comment] 2018-02-03 17:36
Huh, weird.  I've never actually _tried_ following those instructions, so it's good to know that they don't work.  I'll see if I can put together a Mac build soon.

**Comment by ncp1113** [comment] 2018-02-03 17:40
I am trying to help out. If I get one working I will let you know.

**Comment by lexelby** [comment] 2018-02-03 17:42
Thank you!

**Comment by lexelby** [comment] 2018-02-22 03:40
Closing this in favor of concentrating on the portable pyinstaller-based builds.

**Closed by lexelby** 2018-02-22 03:40 UTC
